
Project3: main.o blueMen.o game.o vampire.o  medusa.o harryPotter.o barbarian.o
	g++ main.o blueMen.o game.o vampire.o medusa.o harryPotter.o character.hpp barbarian.cpp -std=c++11 -o Project3

main.o: main.cpp
	g++ -std=c++11 -c main.cpp

blueMen.o: blueMen.cpp
	g++ -std=c++11 -c blueMen.cpp

game.o: game.cpp
	g++ -std=c++11 -c game.cpp

vampire.o: vampire.cpp
	g++ -std=c++11 -c vampire.cpp

medusa.o: medusa.cpp
	g++ -std=c++11 -c medusa.cpp

harryPotter.o: harryPotter.cpp
	g++ -std=c++11 -c harryPotter.cpp

barbarian.o: barbarian.cpp
	g++ -std=c++11 -c barbarian.cpp

clean:
	rm *.o Project3 





